### PR TITLE
[stable/node-problem-detector] bump node-problem-detector to v0.8.7

### PR DESCRIPTION
**Pull request by Constantin07**
## Description

This PR bumps the node-problem-detector to v0.8.7.

Here are the logs:
```bash
 kubectl logs node-problem-detector-b6jsj
I0223 21:26:29.085373       1 log_monitor.go:79] Finish parsing log monitor config file /config/kernel-monitor.json: {WatcherConfig:{Plugin:kmsg PluginConfig:map[] LogPath:/dev/kmsg Lookback:5m Delay:} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock} {Type:ReadonlyFilesystem Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:FilesystemIsNotReadOnly Message:Filesystem is not read-only}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Killed process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB.*} {Type:temporary Condition: Reason:TaskHung Pattern:task [\S ]+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:UnregisterNetDevice Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+} {Type:temporary Condition: Reason:KernelOops Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelOops Pattern:divide error: 0000 \[#\d+\] SMP} {Type:temporary Condition: Reason:Ext4Error Pattern:EXT4-fs error .*} {Type:temporary Condition: Reason:Ext4Warning Pattern:EXT4-fs warning .*} {Type:temporary Condition: Reason:IOError Pattern:Buffer I/O error .*} {Type:temporary Condition: Reason:MemoryReadError Pattern:CE memory read error .*} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:ReadonlyFilesystem Reason:FilesystemIsReadOnly Pattern:Remounting filesystem read-only}] EnableMetricsReporting:0xc000048620}
I0223 21:26:29.085711       1 log_watchers.go:40] Use log watcher of plugin "kmsg"
I0223 21:26:29.086396       1 log_monitor.go:79] Finish parsing log monitor config file /config/docker-monitor.json: {WatcherConfig:{Plugin:journald PluginConfig:map[source:dockerd] LogPath:/var/log/journal Lookback:5m Delay:} BufferSize:10 Source:docker-monitor DefaultConditions:[{Type:CorruptDockerOverlay2 Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:NoCorruptDockerOverlay2 Message:docker overlay2 is functioning properly}] Rules:[{Type:temporary Condition: Reason:CorruptDockerImage Pattern:Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory not empty.*} {Type:permanent Condition:CorruptDockerOverlay2 Reason:CorruptDockerOverlay2 Pattern:returned error: readlink /var/lib/docker/overlay2.*: invalid argument.*} {Type:temporary Condition: Reason:DockerContainerStartupFailure Pattern:OCI runtime start failed: container process is already dead: unknown}] EnableMetricsReporting:0xc000048f8a}
I0223 21:26:29.086609       1 log_watchers.go:40] Use log watcher of plugin "journald"
I0223 21:26:29.088293       1 k8s_exporter.go:54] Waiting for kube-apiserver to be ready (timeout 5m0s)...
I0223 21:26:29.299544       1 node_problem_detector.go:62] K8s exporter started.
I0223 21:26:29.299864       1 node_problem_detector.go:66] Prometheus exporter started.
I0223 21:26:29.299882       1 log_monitor.go:111] Start log monitor /config/kernel-monitor.json
I0223 21:26:29.299939       1 log_monitor.go:111] Start log monitor /config/docker-monitor.json
I0223 21:26:29.383250       1 log_monitor.go:235] Initialize condition generated: [{Type:KernelDeadlock Status:False Transition:2021-02-23 21:26:29.383165428 +0000 UTC m=+0.798982317 Reason:KernelHasNoDeadlock Message:kernel has no deadlock} {Type:ReadonlyFilesystem Status:False Transition:2021-02-23 21:26:29.383165515 +0000 UTC m=+0.798982401 Reason:FilesystemIsNotReadOnly Message:Filesystem is not read-only}]
I0223 21:26:29.385542       1 log_watcher.go:80] Start watching journald
I0223 21:26:29.385569       1 problem_detector.go:67] Problem detector started
I0223 21:26:29.483483       1 log_monitor.go:235] Initialize condition generated: [{Type:CorruptDockerOverlay2 Status:False Transition:2021-02-23 21:26:29.48346421 +0000 UTC m=+0.899281099 Reason:NoCorruptDockerOverlay2 Message:docker overlay2 is functioning properly}]
```

```bash
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  41s   default-scheduler  Successfully assigned default/node-problem-detector-b6jsj to worker-node3.internal
  Normal  Pulling    39s   kubelet            Pulling image "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.7"
  Normal  Pulled     26s   kubelet            Successfully pulled image "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.7" in 13.224430975s
  Normal  Created    26s   kubelet            Created container node-problem-detector
  Normal  Started    25s   kubelet            Started container node-problem-detector

```

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [] Github actions are passing

### CODE REVIEW

**Comment by Constantin07** [comment]
I did run `docker run --rm -v "$PWD:/helm-docs" jnorwood/helm-docs:v0.14.0 --template-file=../../ci/README.md.gotmpl` to update README.md but it still fails ...

**Comment by max-rocket-internet** [comment]
> update README.md but it still fails ...

Did you run it from repo root?

Anyway, I've run it for you and commited the changes to your fork/branch 🙂

**Review by max-rocket-internet — APPROVED** [review]
Thank you @Constantin07 💛

**Comment by Constantin07** [comment]
> Did you run it from repo root?

No, from chart directory.

Thank you @max-rocket-internet

**Pull request merged**
