### PR TITLE
[stable/k8s-resources]: support ClusterRoles and ClusterRoleBindings

### PR DESCRIPTION
**Pull request by eshepelyuk**
## Description

Adding `ClusterRole` and `ClusterRoleBinding` resources support.

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
- [x] Github actions are passing

### CODE REVIEW

**Comment by eshepelyuk** [comment]
Hello

Although tests are passing locally - to run on GH - the approval is needed, so I haven't ticked a checkbox in PR decsription yet

**Comment by eshepelyuk** [comment]
@max-rocket-internet shouldn't [this chart](https://github.com/deliveryhero/helm-charts/tree/master/stable/service-account) be deprecated in favour of `k8s-resources` ?

**Review by max-rocket-internet — APPROVED** [review]
Thanks @eshepelyuk 💕

**Comment by max-rocket-internet** [comment]
> shouldn't [this chart](https://github.com/deliveryhero/helm-charts/tree/master/stable/service-account) be deprecated in favour of k8s-resources ?

In theory I guess but I think they can coexist 🙂

**Pull request merged**
