### PR TITLE
[stable/locust] Add update strategy to values

### PR DESCRIPTION
**Pull request by zabudskyi**
## Description

Added possibility to set update strategy. Should be merged after https://github.com/deliveryhero/helm-charts/pull/82, if it looks fine.

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [ ] Github actions are passing

### CODE REVIEW

**Comment by zabudskyi** [comment]
I run helm-docs for Readme and output doesn't look well.
It removes `How to install this chart` section

This change doesn't look fine as `strategy` does not only have `type` but `rollingUpdate` section as option too.

```
-| master.strategy | object | `{}` |  |
+| master.strategy.type | string | `"RollingUpdate"` |  |
 | nameOverride | string | `""` |  |
 | nodeSelector | object | `{}` |  |
 | podSecurityContext | object | `{}` |  |
@@ -112,10 +86,7 @@ helm install my-release deliveryhero/locust -f values.yaml
 | worker.replicas | int | `1` |  |
 | worker.resources | object | `{}` | resources for the locust worker |
 | worker.serviceAccountAnnotations | object | `{}` |  |
-| worker.strategy | object | `{}` |  |
-
+| worker.strategy.type | string | `"RollingUpdate"` |  |
```

**Comment by max-rocket-internet** [comment]
> It removes How to install this chart section

I don't see this when I checkout your branch?

> +| worker.strategy.type | string | `"RollingUpdate"` |  |

I think this makes sense, no?

**Review by max-rocket-internet — APPROVED** [review]
Fix the docs and then we can merge

**Comment by zabudskyi** [comment]
It can be 
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100
      maxSurge: 50%
```
So `worker.strategy.type` doesn't look well as value description because `worker.strategy` is value to be set in this case.
I'll try to use `worker.strategy.type` to pass the check

**Comment by max-rocket-internet** [comment]
Thanks @zabudskyi

**Pull request merged**
