### PR TITLE
[stable/cluster-overprovisioner] Add service account to cluster-overprovisioner chart

### PR DESCRIPTION
**Pull request by joshuastern**
## Description

Add ability to use a non-default service account for the cluster-overprovisioner

## Checklist

- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] Github actions are passing

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Hi @joshuastern, thanks for the PR. Can you fix the docs? Details are here: https://github.com/deliveryhero/helm-charts#contributing

Also, I'm curious, why does `cluster-overprovisioner` need a serviceAccount? It just runs and does nothing, doesn't need to connect to the k8s API etc?

**Comment by joshuastern** [comment]
> Hi @joshuastern, thanks for the PR. Can you fix the docs? Details are here: https://github.com/deliveryhero/helm-charts#contributing
> 
> Also, I'm curious, why does `cluster-overprovisioner` need a serviceAccount? It just runs and does nothing, doesn't need to connect to the k8s API etc?

Exactly, it does not need a service account token. That's why we intend to set the `automountServiceAccountToken` to false when installing the chart. I could set the default value for this to `false`, but it seems better to keep it consistent with the default kubernetes behavior.

**Comment by max-rocket-internet** [comment]
> Exactly, it does not need a service account token. That's why we intend to set the automountServiceAccountToken to false

I still don't get the point though. You just want to have the pods running without the token?

**Comment by joshuastern** [comment]
> > Exactly, it does not need a service account token. That's why we intend to set the automountServiceAccountToken to false
> 
> I still don't get the point though. You just want to have the pods running without the token? Therefore you create a new serviceAccount so that you can set `automountServiceAccountToken` to false?

Yup. In its current state, it runs with a token for the default service account.

**Review by max-rocket-internet — APPROVED** [review]
Makes sense. Thanks!

**Comment by max-rocket-internet** [comment]
@joshuastern the CI test for markdown lint has started failing for some reason. I will investigate.

**Comment by max-rocket-internet** [comment]
I opened an issue here: https://github.com/avto-dev/markdown-lint/issues/13

**Pull request merged**
