### PR TITLE
[stable/locust] Adding hostAliases to locust template

### PR DESCRIPTION
**Pull request by abdullazin**
## Description
This change allows the user to override the hosts file entries on the pod. This is very useful when the server you're load testing is not published on any DNS.

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
- [x] Github actions are passing

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Thanks for the PR @abdullazin but you need to follow the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr) in order for the CI to pass.

**Comment by abdullazin** [comment]
@max-rocket-internet Can I get another review please? All the checks are passing

**Comment by max-rocket-internet** [comment]
Hi @abdullazin, you need to add `hostAliases` to `values.yaml`, commented out but with comment structured so the README is automatically updated with the description of the value 🙂

For example: https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/values.yaml#L19-L20

**Comment by abdullazin** [comment]
@max-rocket-internet thank you! I added it to the `values.yaml` and added a small description as well. Could you please re-review my changes?

**Review by max-rocket-internet — APPROVED** [review]
Looks great, thanks @abdullazin 💚

**Pull request merged**
