### PR TITLE
[stable/kube-downscaler] Enable the addition of pod annotations

### PR DESCRIPTION
**Pull request by doncraig**
## Description

Allow the user to add pod annotations as per the incubator/kube-downscaler chart

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [ ] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [ ] Github actions are passing

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
@doncraig please review the second checkbox 🙂

**Comment by doncraig** [comment]
@max-rocket-internet I'm confused as to why this is failing. I did regenerate the docs and stable/kube-downscaler/README.md is included in the PR

**Comment by max-rocket-internet** [comment]
@doncraig 

> I'm confused as to why this is failing.

I think you didn't commit all the changes after running the command? For example, the chart version is not updated in the README. Check this PR for example: https://github.com/deliveryhero/helm-charts/pull/204/files#diff-5fc4e99aeb536607a094704cacc7a1ac1b2c4c02d073fc6ad2e23b976da7406e

**Comment by max-rocket-internet** [comment]
I'll close this but feel free to reopen when you're ready to work on it again.

**Pull request closed without merging**
