### PR TITLE
[stable/kube-downscaler] Kube-Downscaler does not respect release namespace when templating

### PR DESCRIPTION
**Pull request by hlascelles**
The `kube-downscaler` helm chart doesn't honour the namespace passed in to helm. This is because the chart is missing the typical metadata configuration on its kubernetes resources. ie, this problem is the same as this one for another chart: https://github.com/deliveryhero/helm-charts/issues/216

To reproduce this problem:

```bash
helm fetch deliveryhero/kube-downscaler --version 0.7.4 --untar=true
helm template my-release kube-downscaler --namespace kube-system  > kube-downscaler.yaml
```

The `deployment.yaml` and other files will have no namespace. ie, it is not configured here: https://github.com/deliveryhero/helm-charts/blob/0b420820e3f88d5e7f9f10ddd1c9a029adb9a422/stable/kube-downscaler/templates/deployment.yaml#L3

Fix is as below for the required resources:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullname }}-{{ .name }}"
  namespace: {{ .Release.Namespace }}
```

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
- [ ] Github actions are passing

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
@hlascelles there was a checklist of items that are required to make a PR mergeable that you deleted when you opened the PR 😃

https://github.com/deliveryhero/helm-charts/blob/master/.github/pull_request_template.md#checklist

**Comment by hlascelles** [comment]
Nice! Hmm, that doc regenerate wiped out a lot. Is that right?

**Comment by max-rocket-internet** [comment]
> Nice! Hmm, that doc regenerate wiped out a lot. Is that right?

Not right, you need to run it from repo root

**Review by max-rocket-internet — APPROVED** [review]
Nice, thanks @hlascelles 💜

**Pull request merged**
