### PR TITLE
[stable/kube-downscaler] sync cluster role with upstream

### PR DESCRIPTION
**Pull request by runningman84**
same rules as upstream project:
https://codeberg.org/hjacobs/kube-downscaler/src/branch/main/deploy/rbac.yaml

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [ ] Github actions are passing

### CODE REVIEW

**Review by max-rocket-internet — APPROVED** [review]
Thanks @runningman84 ! You'll also need to update the readme for CI to pass

**Comment by runningman84** [comment]
Ok I have updated the readme

**Comment by runningman84** [comment]
@max-rocket-internet what needs to be done to rerun the checks and merge it?

**Comment by max-rocket-internet** [comment]
@runningman84 I don't know, all the checks are queued 🤔

**Comment by max-rocket-internet** [comment]
I can't cancel them either. @runningman84 can you make another dummy commit to try and restart the actions?

**Pull request merged**
