### PR TITLE
[stable/aws-s3-proxy]: provide support for serviceAccount annotations

### PR DESCRIPTION
**Pull request by alekc**
## Description
This PR adds support for service account annotations.

## Checklist

- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [ ] Github actions are passing

### CODE REVIEW

**Review by max-rocket-internet — APPROVED** [review]

**Review by max-rocket-internet — APPROVED** [review]

**Comment by max-rocket-internet** [comment]
@alekc I can't update your branch on this PR so you need to rebase or merge master into your branch.

**Comment by alekc** [comment]
@max-rocket-internet I merged the master branch to get it up to speed. Could you start the workflow?

**Comment by max-rocket-internet** [comment]
@alekc it's already out of date again as there are many commits to this repo. Normally there is an a button that allows me to update your branch:

Screenshot 2021-08-17 at 19 05 55

But it's missing on this PR, probably because you removed this access or because you've created a PR for a branch that is not in your own account.

**Comment by alekc** [comment]
weird. If we do not manage to get to the release this time around either feel free to close the pr? Not sure what else can be done.

**Comment by alekc** [comment]
Also, the aut-merge is correctly enabled, the issue which prevents the merge is that I cannot start the pipelines for checking.

**Comment by max-rocket-internet** [comment]
Merged, finally 🙂 Thanks @alekc!

**Pull request merged**
